### PR TITLE
Bandwidth

### PR DESCRIPTION
**Pull request by willmcgugan**
### What this PR solves
- Fixes a bug in port forwarding where the threads persisted sending over a closed channel. Had no real symptoms other than wasting bandwidth.
- Added a CHUNK_SIZE constant used when copying data to m2m.
- Upgrades Lomond, which adds proxy support, and some optimisations. New Lomond also supports compression, but that is disabled until we have a mechanism to selectively enable it for compressible fle types.
 

### Review
- [X] Ready for review

### CODE REVIEW

**Comment by barfle** [comment]
How does one enable proxy support in this version of the agent?

**Comment by willmcgugan** [comment]
@barfle is enabled by default. Will use standard environment variables

**Comment by barfle** [comment]
Yes, but what I mean is where does one set those environment variables? In supervisor somewhere?

**Comment by willmcgugan** [comment]
I think it is OS dependant. But there is generally UI in linux for it that I'm guessing writes it to one of the bash start script.

I would expect that supervisor inherits those env vars when running agent. But I'm sure that you could override them in supervisor if you wanted to.

**Pull request merged**
